---
title: "Data Review"
date: "4/23/2020"
output:
  html_document:
    df_print: kable
    fig_caption: true
    dev: svg
    highlight: haddock
    keep_md: no
    smart: no
    theme: journal
    css: "../common/journalnps.min.css"
    toc: yes
    toc_float: true
    number_sections: true

---

```{r setup, include=FALSE}
RRpackages <- c('markdown',     # links to Sundown rendering library
                'rmarkdown',    # newer rendering via pandoc
                'pander',       # alternative renderer for markdown,
                                # plus better tables than just knitr
                'knitr',
                "devtools",
                "R.rsp",        # dynamic generation of scientific reports
                "rmdHelpers",   # misc from Mark Peterson
                                #  thisFileName() thisFile_knit()
                'yaml',         # format data into markdown
                'kableExtra',
                'rmdformats',   # templates including automatic ToC,
                                # also use_bookdown()
                'htmltools'     #
                )

inst <- RRpackages %in% installed.packages()
if (length(RRpackages[!inst]) > 0) {
   install.packages(RRpackages[!inst], dep = TRUE)
}
lapply(RRpackages, library, character.only = TRUE)

knitr::opts_chunk$set(
   echo = TRUE,
   comment = " ",
   dev = "svg",
   tidy.opts = list(width.cutoff = 60),
   tidy = TRUE
   )

```

Data releases require a minimum of one review of the data and one review of the accompanying metadata. The special focus of the data reviewer is the accuracy, completeness, and usability of a data product. The following checklist is provided for the assistance of data package reviewers who are experienced in working with the particular type of data being reviewed. It is assumed that data reviewers have the expertise and tools to access and assess both the data and the metadata, and are familiar with standard practices within the relevant discipline for the formatting and presentation of data. 

The Inventory & Monitoring Division is moving toward publishing datasets in data packages, which contain datasets, metadata, and a “manifest” file describing the package contents. When reviewing data packages all three components must be reviewed. The data reviewer may also serve as the metadata and manifest reviewer.

*Note that NPS and IMD have not yet established guidance for conducting data reviews; only that appropriate review is conducted prior to release of scientific information, including data. The following is based on USGS data release checklists and is currently employed by the IMD Central Office staff in implementation of the national Environmental Settings monitoring protocol and the Inventories 2.0 program.*

# Data Sets
In some cases, it will be unreasonable to actually check every data value, so a spot check or a check of a carefully selected sample may need to suffice. In this case, the data review report should indicate that a spot check or selected sample was examined.

A data review should consider the following:

## Data Technical Review
- Are the data what the author says they are? 
- Are data values reasonable? Do they meet specifications for quality, accuracy, and completeness as identified by both the author and the approving official? This might include specific checks such as:
  - Are they in a valid range for that measurement?
  - Do they display seasonal or daily trends that are expected? Is there consistency between adjacent or otherwise related datasets, within the product?
  - Are the geographic locations given for the data reasonable? (e.g., are ocean data  points actually showing in the ocean?)
  - Is the accuracy claimed for the data reasonable?
  - Are data anomalies or gaps explained in the metadata? Are “no data” values accurately defined? Do analysis values add up?
- Do summary statistics of data within the dataset (fields, categories, record counts, and codes) match what is presented in the data release report?
- Does the dataset contain data that are outside of or inconsistent with enumerated domains?

## Data Usability Review
- Does the product as a whole, through its design or documentation, provide enough information so that the data and metadata can be easily accessed and used? 
- For data packages created using the IMD Data Release Report template, these should be checked using the DSTools package to ensure:
  - Can the data package be downloaded and unpacked in an R environment? Note that DSTools will not import data fields in cases where there is a mismatch between data structure and metadata description.
  - Are the columns the appropriate and expected class?
  - Are the factor levels for enumerated domains imported properly?
- Is versioning information provided, if warranted?
- Are all fields and enumerated domains defined and understandable without reference to the protocol, report, or other external documentation?
- Does the dataset or metadata include the misuse of “reserved” codes
  - NC for anything other than “No Change”
  - NA for anything other than “Not Applicable” or “Not Available” 
- Do qualification codes use numbers in lieu of codes? Note: this may be okay in some circumstances but numbers are generally not descriptive.
- Do codes (qualification or otherwise) mean different things for different fields?
- Do enumerated domains contain options that are not holistic of all options (i.e., limited to only those values present within the data set as opposed to all that are applicable)?
- Does the dataset use consistent units within and among fields within a database? Note: all should be SI units (preferred option), but at the very least should be consistently English or metric within a given data set unless professional norms dictate otherwise (hydrology flows are typically reported in cfs as opposed to the SI equivalent, for example).
- Do codes and definitions for fields match what’s presented in the data release report?
- Do datasets, manifests, and metadata all clearly indicate whether a dataset contains data that are protected from release? 

# Metadata
- Do all fields with enumerated domains have definitions for all possible (as opposed to all used) domains?
- Are all fields of the appropriate format for the type of data they contain (numeric, string, date, logical)?
- Is the metadata in either FGDC, EML, or ISO format and does it validate as such?
- Does the title convey the “what, where, when, who, and (if applicable) scale” of the data?
- Does the abstract provide a short statement that allows users to quickly evaluate the content of the dataset?
- Are the coordinate system and datum defined appropriately (both horizontal and vertical)?
- Is sample design information included (where appropriate)?
- Is geographic coverage information included and appropriate for the dataset?
- For data with biological observations, does it include the taxonomy elements for what was observed and what was surveyed?

# Manifests
Note that the following may change as standards for manifest files are developed (and may be more than what is ultimately required).

- Does the manifest file list and describe all contents in the data package?
- Does the manifest file contain Data Store reference/links to accompanying data publication report?
- Does the manifest file contain Data Store reference/links to protocol/study plan, SOPs (optional since there may be deviations described in the report), and where applicable DQS/QAP?
- Does the manifest file contain Data Store reference/links to itself?

# Special Notes for Data Packages containing Protected Data
- Do uncensored versions of data packages contain clear indications of exactly what data are to be protected from accidental release and how (and to whom) release is appropriate?
- Does the data package report explain whether, how, and why data are obscured from release?
- Are methods for data protection consistent with rules established by the park(s) where data were collected?
- In general, data sets with data to be protected should have a “real” and an “obscured” version of data. Public versions should delete any “Real” data columns that are not to be made public rather than replacing values in the actual data fields.
- Do data packages with censored data clearly indicate that data have been obscured?

# Data Package Consistency 
- Are titles for data packages consistent across metadata, manifests, the data release report, and the Data Store reference?
- Is the abstract consistent across metadata, manifests, the data release report, and the Data Store reference?


